version: "3.9"

services:
  minio:
    image: minio/minio
    container_name: minio
    command: "server /data --console-address ':9001'"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - codewaffle-auto-update
    environment:
      - "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

  createbuckets:
    image: minio/mc
    container_name: setup
    depends_on:
      - minio
    networks:
      - codewaffle-auto-update
    entrypoint: >
      /bin/sh -c "
      sleep 10s;
      /usr/bin/mc alias set myminio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb myminio/codewaffle-test;
      /usr/bin/mc policy set public myminio/codewaffle-test;
      exit 0;
      "

networks:
  codewaffle-auto-update:
