name: pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile

  package:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn package
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./packages/**/dist

  lint:
    runs-on: ubuntu-latest
    needs: [package]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: package
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn check:types
      - run: yarn lint:ci

  test:
    runs-on: ubuntu-latest
    needs: [package]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: package
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn test:ci

  build-web:
    runs-on: ubuntu-latest
    needs: [package]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: package
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build:web

  # https://playwright.dev/docs/ci#github-actions
  e2e-web:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [package]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: package
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: npx playwright install --with-deps
      - run: yarn e2e:web
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: e2e-web-report
          path: playwright-report/
          retention-days: 30
