name: pull requests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn check:types
      - run: yarn lint:ci

  test:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn test

  build-web:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: build-web
          path: build
          retention-days: 5

  build-native:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn package
      - uses: actions/upload-artifact@v3
        with:
          name: build-native
          path: |
            .webpack
            out
          retention-days: 5

  # https://playwright.dev/docs/ci#github-actions
  e2e-web:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [build-web]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - uses: actions/download-artifact@v3
        with:
          name: build-web
          path: build
      - run: yarn install --frozen-lockfile
      - run: npx playwright install --with-deps
      - run: yarn e2e:web
      - uses: actions/upload-artifact@v3
        with:
          name: e2e-web-report
          path: playwright-report
          retention-days: 5

  e2e-native:
    timeout-minutes: 60
    runs-on: macos-latest
    needs: [build-native]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - uses: actions/download-artifact@v3
        with:
          name: build-native
          path: ./
      - run: yarn install --frozen-lockfile
      - run: npx playwright install --with-deps
      - run: yarn e2e:native
      - uses: actions/upload-artifact@v3
        with:
          name: e2e-native-report
          path: playwright-report
          retention-days: 5
